name: Build Zirkonium 1.21.4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK
        uses: graalvm/setup-graalvm@main
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"

      - name: Apply patches
        run: ./gradlew -Dorg.gradle.jvmargs="-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector" applyAllPatches --stacktrace --no-daemon
      - name: Create MojmapPaperclipJar
        run: ./gradlew -Dorg.gradle.jvmargs="-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector" createMojmapPaperclipJar --stacktrace --no-daemon
      - name: Create ReobfPaperclipJar
        run: ./gradlew -Dorg.gradle.jvmargs="-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector" -Dpaperweight.debug=true createReobfPaperclipJar --stacktrace --no-daemon

      - name: Rename Paperclip Jar
        run: |
          mv zirkonium-server/build/libs/zirkonium-paperclip-1.21.4-R0.1-SNAPSHOT-mojmap.jar ./zirkonium-1.21.4-mojmap.jar
          mv zirkonium-server/build/libs/zirkonium-paperclip-1.21.4-R0.1-SNAPSHOT-reobf.jar ./zirkonium-1.21.4-reobf.jar

      - name: Upload Zirkonium
        uses: actions/upload-artifact@main
        with:
          name: Zirkonium 1.21.4
          path: ./zirkonium-1.21.4-*.jar

      - name: Rename Zirkonium Jar
        run: |
          mv ./zirkonium-1.21.4-mojmap.jar ./zirkonium-1.21.4.jar

      - name: Release Zirkonium
        if: github.event_name != 'pull_request'
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "Zirkonium 1.21.4"
          automatic_release_tag: "ver-1.21.4"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "./zirkonium-1.21.4.jar"
          prerelease: false