name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "ver/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Configure Git
        run: git config --global user.email "action@github.com" && git config --global user.name "Github Action"
      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build
        run: ./gradlew build --stacktrace